<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Riskified.SDK.Sample</AssemblyName>
    <RootNamespace>Riskified.SDK.Sample</RootNamespace>

    <!-- Language & Code Quality -->
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <!-- Reference to the SDK project -->
    <ProjectReference Include="..\Riskified.SDK\Riskified.SDK.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!-- Include App.config in output -->
    <None Update="App.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
